theme: jekyll-theme-minimal
title: Stephen Lenane
description: Freelance full-stack software developer based in Galway, Ireland

[Email](mailto:info@stephenlenane.com) / [Website](https://www.stephenlenane.com/) / [LinkedIn](https://www.linkedin.com/in/stephen-lenane-6756a0228/) / [GitHub](https://github.com/slenane)
